# Generated by Django 4.1.7 on 2023-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streeyaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='media'),
        ),
    ]
