# Generated by Django 4.1.7 on 2023-04-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streeyaapp', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streeyaapp.itemsize'),
            preserve_default=False,
        ),
    ]
