# Generated by Django 4.1.7 on 2023-05-01 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streeyaapp', '0004_cart_item_qty_cart_item_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('staff_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('area', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('alternet_contact', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
